### PR TITLE
Ukrainian translation file

### PR DESCRIPTION
**Pull request by Yuraplonka**
[uk_ua.zip](https://github.com/VsnGamer/ElevatorMod/files/5207540/uk_ua.zip)

### CODE REVIEW

**Comment by VsnGamer** [comment]
This pull request is not correct but dont worry I will include your translation file myself
Thanks!

**Comment by VsnGamer** [comment]
Also could you also do the translation for the more recent versions (1.16)?
There are just a few new lines.

**Comment by Yuraplonka** [comment]
Yes, of course

**Comment by Yuraplonka** [comment]
but now i don't have access to pc

**Comment by Yuraplonka** [comment]
i just couldn't send another file extension

**Pull request closed without merging**
